In [49]:
import numpy as np

np.set_printoptions(suppress=True)

<h2>ÁLGEBRA LINEAL</h2>

Si $AB = I = BA$ se dice que $B$ es la inversa de $A$ y se denota como $A^1$

In [9]:
A = np.array([
    [1, 2, 1],
    [4, 4, 5],
    [6, 7, 7]
])

B = np.array([
    [-7, -7, 6],
    [2, 1, -1],
    [4, 5, -4]
])

In [27]:
# Multiplicamos las matrices de ambas formas
AB = np.dot(A, B)
BA = np.dot(B, A)

In [29]:
print(AB)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [30]:
print(BA)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [28]:
print(np.array_equal(AB, BA))

True


La transpuesta de una matriz se obtiene cuando conviertes sus filas en columnas y se escribe como $A^T$

In [21]:
print(A)

[[1 2 1]
 [4 4 5]
 [6 7 7]]


In [31]:
print(A.T)

[[1 4 6]
 [2 4 7]
 [1 5 7]]


Algunas propiedades de las inversas y transpuestas son:

In [80]:
A = np.array([[1, 2, 0],
              [0, 1, 3],
              [4, 0, 1]])

B = np.array([[2, 0, 1],
              [1, 1, 0],
              [3, 1, 2]])

$AA^{-1} = I = A^{-1}A$ (la verificamos hace un momento)

$ (AB)^{-1} = B^{-1}A^{-1} $

In [81]:
print(CL := np.linalg.inv(A @ B))

[[ 0.36 -0.22  0.16]
 [ 0.12  0.26 -0.28]
 [-0.68  0.36 -0.08]]


In [82]:
print(CR := np.linalg.inv(B) @ np.linalg.inv(A))

[[ 0.36 -0.22  0.16]
 [ 0.12  0.26 -0.28]
 [-0.68  0.36 -0.08]]


In [83]:
print(np.allclose(CL, CR))

True


$ (A + B)^{-1} \neq A^{-1} + B^{-1} $

In [84]:
print(CL := np.linalg.inv(A + B))

[[ 0.09375 -0.15625  0.125  ]
 [ 0.5625   0.0625  -0.25   ]
 [-0.40625  0.34375  0.125  ]]


In [85]:
print(CR := np.linalg.inv(A) + np.linalg.inv(B))

[[ 1.04  0.42 -0.26]
 [-0.52  0.54  0.38]
 [-1.16 -0.68  1.04]]


In [86]:
print(np.allclose(CL, CR))

False


$ (A^T)^T = A $

In [87]:
print(A)

[[1 2 0]
 [0 1 3]
 [4 0 1]]


In [88]:
print(A_T := A.T)

[[1 0 4]
 [2 1 0]
 [0 3 1]]


In [89]:
print(A_T.T)

[[1 2 0]
 [0 1 3]
 [4 0 1]]


In [90]:
print(np.array_equal(A, A_T.T))

True


$ (AB)^T = B^TA^T $

In [91]:
print(CL := (A @ B).T)

[[ 4 10 11]
 [ 2  4  1]
 [ 1  6  6]]


In [92]:
print(CR := B.T @ A.T)

[[ 4 10 11]
 [ 2  4  1]
 [ 1  6  6]]


In [93]:
print(np.array_equal(CL, CR))

True


$ (A + B)^T = A^T + B^T $

In [94]:
print(CL := (A + B).T)

[[3 1 7]
 [2 2 1]
 [1 3 3]]


In [95]:
print(CR := A.T + B.T)

[[3 1 7]
 [2 2 1]
 [1 3 3]]


In [97]:
print(np.array_equal(CL, CR))

True


Una matriz simétrica es la que $A = A^T$, nótese que esto solo puede pasar con matrices cuadradas. La suma de dos matrices simétricas es también simétrica, el producto no siempre.
$$\begin{bmatrix} 1 & 0 \\ 0 & 0 \end{bmatrix}
\begin{bmatrix} 1 & 1 \\ 1 & 1 \end{bmatrix}
=
\begin{bmatrix} 1 & 1 \\ 0 & 0 \end{bmatrix}$$
Por otro lado, si $A$ es invertible entonces $A^T$ también lo es. De modo que $(A^T)^{-1} = (A^{-1})^T$

In [98]:
print(CL := np.linalg.inv(A.T))

[[ 0.04  0.48 -0.16]
 [-0.08  0.04  0.32]
 [ 0.24 -0.12  0.04]]


In [99]:
print(CR := (np.linalg.inv(A)).T)

[[ 0.04  0.48 -0.16]
 [-0.08  0.04  0.32]
 [ 0.24 -0.12  0.04]]


In [101]:
print(np.allclose(CL, CR))

True
