In [1]:
import numpy as np
import pandas as pd
pd.options.display.max_columns = 20
pd.options.display.max_rows = 20
pd.options.display.max_colwidth = 80
np.set_printoptions(precision=4, suppress=True)

In [2]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

Los arreglos de NumPy son mucho más veloces al realizar operaciones con ellos y se nota en arreglos muy grandes

In [3]:
%timeit my_arr2 = my_arr * 2

1.14 ms ± 28.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [4]:
%timeit my_list2 = [x * 2 for x in my_list]

24.3 ms ± 594 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
data = np.array([[1.5, 0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5,  0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [6]:
data * 10

array([[ 15.,   1.,  30.],
       [  0., -30.,  65.]])

In [7]:
data + data

array([[ 3. ,  0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

In [10]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr2.ndim

2

In [13]:
arr2.shape

(2, 4)

In [14]:
arr1.dtype
arr2.dtype

dtype('int64')

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.empty((2, 3, 2))

array([[[nan,  0.],
        [nan,  0.],
        [-0.,  0.]],

       [[-0.,  0.],
        [-0.,  0.],
        [ 0.,  0.]]])

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
arr_int64 = np.full((2, 3), 4, np.float32)
arr_int64

array([[4., 4., 4.],
       [4., 4., 4.]], dtype=float32)

In [22]:
arr_int64.astype(np.float32)

array([[4., 4., 4.],
       [4., 4., 4.]], dtype=float32)

In [23]:
np.array(["1", "2", "3"]).astype(np.int64)

array([1, 2, 3])

In [24]:
arr1 = np.arange(1, 10)
arr2 = np.arange(1, 4)


In [25]:
arr1[1:3] = 100
arr1

array([  1, 100, 100,   4,   5,   6,   7,   8,   9])

In [26]:
array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
array3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
old_values = array3d[0].copy()
array3d[0] = 100
array3d

array([[[100, 100, 100],
        [100, 100, 100]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [28]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
array3d[0] = old_values
array3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
identity = np.eye(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
identity[3:, :]

array([[0., 0., 0., 1.]])

In [32]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0,2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])

In [33]:
new_data = data[(names != "Bob") & (names == "Joe")]
new_data[new_data < 0] = 100
new_data

array([[  0,   2],
       [100, 100],
       [  3,   4]])

In [34]:
data[names != "Bob"]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

Fancy indexing

In [35]:
arr = np.zeros((8, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
for i in range(8):
    arr[i] = str(i)

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [37]:
arr[[-1, -7]]

array([[7., 7., 7., 7.],
       [1., 1., 1., 1.]])

In [38]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [39]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [40]:
arr2 = arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]
arr2

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [41]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]] = 100
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [42]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [43]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [44]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [45]:
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [ ]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [ ]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [ ]:
arr.swapaxes(0, 1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])